# Config file for test_mnist.py

# meta parameters
meta:
  exp_id: 1
  model_name: 'mnist_exp_at_seed91'
  save_path: './'
  data_path: '~/data/'
  seed: 2019
  gpu_id: '0'

test:
  batch_size: 500
  num_test_samples: 10000

bb: False

# parameters for pgd attack
pgd:
  plus: False  # whether to use PGD+
  random_start: True
  loss_func: 'ce'
  rand_eps: 0
  clip: True
  init_mode: 1
  num_restarts: 5
  quant: False

  # parameters for AT with l-inf norm
  p: 'inf'
  epsilon: 0.3
  num_steps: 100
  step_size: 0.01
