# Config file for test_mnist.py

# meta parameters
meta:
  exp_id: 1
  model_name: 'mnist_ates_exp'
  save_path: './'
  data_path: '~/data/'
  seed: 2019
  gpu_id: '0'

test:
  batch_size: 500
  num_test_samples: 10000

bb: False

# parameters for pgd attack
pgd:
  plus: False  # whether to use PGD+
  random_start: True
  loss_func: 'ce'
  rand_eps: 0
  clip: True
  init_mode: 1
  num_restarts: 5
  quant: False

  # parameters for AT with l-inf norm
  p: 'inf'
  epsilon: 0.3
  num_steps: 100
  step_size: 0.01

rand:
  seed: 202
  clip: [0, 1]
  # clip: [-1., 1.]
  # clip: [0., 1.]
  num_draws: 3
  # transforms: ['drop_pixel']
  # transforms: ['erase']
  # transforms: ['normal']
  transforms: ['uniform', 'hflip', 'gamma', 'normal']
  # transforms: ['normal', 'shear', 'scale', 'rotate', 'translate']
  # transforms: ['normal', 'affine']
  # transforms: ['colorjitter']
  # transforms: ['colorjitter', 'motionblur', 'erase', 'shear', 'scale', 'rotate', 'translate']
  # transforms: ['motionblur']
  # transforms: ['rotate', 'motionblur', 'translate', 'colorjitter', 'shear', 'scale']
  # transforms: ['drop_pixel', 'rotate', 'translate', 'colorjitter', 'shear', 'scale']
  # transforms: ['hflip', 'drop_pixel', 'rotate', 'translate', 'colorjitter', 'shear', 'gamma', 'scale', 'grayscale']
  # transforms: ['hflip', 'drop_pixel', 'colorjitter', 'gamma', 'grayscale']
  # transforms: ['hflip', 'drop_pixel', 'colorjitter']
  # transforms: ['hflip', 'normal', 'colorjitter', 'gamma', 'grayscale', 'drop_pixel', 'affine']
  # transforms: ['medblur', 'hflip', 'normal', 'motionblur', 'gamma', 'laplacian', 'drop_pixel', 'gaussblur', 'affine', 'boxblur', 'sobel']
  affine:
    dist: 'uniform'
    alpha: 0.3
  boxblur:
    p: 0.2
    kernel_size: 3
  colorjitter:
    alpha: 0.5
  drop:
    p: 0.3
  drop_pixel:
    p: 0.4
  erase:
    # scale: [0.1, 0.2]    # scale of area
    scale: [0.0000001, 0.5]
    ratio: [0.5, 2.0]    # aspect ratio of the erasing box
  gamma:
    dist: 'uniform'
    alpha: 0.3
  gaussblur:
    p: 0.2
    kernel_size: 3
    sigma: 1
  grayscale:
    p: 0.2
  hflip:
    p: 0.5
  laplacian:
    p: 0.2
    kernel_size: 3
  medblur:
    p: 0.2
    kernel_size: 3
  motionblur:
    p: 0.2
    kernel_size: 3
    angle: 90.0
    direction: 1.0
  normal:
    mean: 0.0
    std: 0.2
    # clip: [0., 1.]
    clip: null
  rotate:
    dist: 'uniform'
    alpha: 30
  scale:
    dist: 'uniform'
    alpha: 0.3
  shear:
    dist: 'uniform'
    alpha: 0.3
  sobel:
    p: 0.2
  translate:
    dist: 'uniform'
    alpha: 0.3
  uniform:
    range: [-0.2, 0.2]
