# Config file for train.py

# ============================= meta parameters ============================= #
meta:
  exp_id: 1             # experiment id
  model_name: 'mnist_rand'      # model name. If null, automatically generate it.
  save_path: './'       # path to save model weights
  data_path: '~/data/'  # path to dataset
  seed: 2020            # set random seed
  gpu_id: '0'           # set id of GPU to use (e.g., '0' or '0, 1')
  dataset: 'mnist'
  normalize: null
  # normalize: # ImageNet
  #   mean: [0.485, 0.456, 0.406]
  #   std: [0.229, 0.224, 0.225]
  network: 'basic'
  val_size: 0.1
  batch_size: 400        # training and evaluation batch size
  # epochs: 70             # total number of epochs to train
  # learning_rate: 1.0e-2  # learning rate
  # l2_reg: 5.0e-4         # L2-regularization or weight decay parameter
  epochs: 70
  learning_rate: 1.0e-1
  l2_reg: 5.0e-4
  augment: False
  save_best_only: True   # if True, only save best model
  save_epochs: 1         # used when <save_best_only> is False. Save model every specified epochs
  lr_scheduler: 'step'   # learning rate schedule (options: null, 'step', 'cyclic')
  method: 'pgd-rand'         # training method (options: 'pgd', 'fgsm', 'rand', 'pgd-rand', 'none' = normal training)

# train:
#   batch_size: 400
#   epochs: 5
#   l2_reg: 0.0005
#   learning_rate: 0.01
#   lr_scheduler: step
#   save_best_only: true
#   save_epochs: 1

# =================== parameters for adversarial training =================== #
at:
  random_start: True    # if True, use random start
  loss_func: 'ce'       # loss function for generating adversarial examples (options: 'ce', 'hinge', 'clipped_ce', 'trades')
  use_diff_rand_eps: False    # if True, use random start with perturbation size of <rand_eps> instead of <epsilon>
  rand_eps: 0
  clip: [0., 1.]            # if True, clip adversarial input to [0, 1]
  beta: 0               # TRADES parameters
  method: 'pgd'

  # parameters for AT with l-inf norm
  p: 'inf'              # specify lp-norm to use
  epsilon: 0.3          # perturbation magnitude
  num_steps: 40         # number of PGD steps
  step_size: 0.02       # PGD step size

  # p: '2'
  # epsilon: 1.0
  # num_steps: 10
  # step_size: 0.25

  # parameters for ATES
  early_stop: False         # if True, use AT with early stop (ATES)
  init_gap: 0               # initial softmax probability gap
  final_gap: 1              # final softmax probability gap
  step_gap: [30, 45, 60]    # specify schedule for probability gap
  linear_gap: null
  # step_gap: null
  # linear_gap: [30, 70]

  # parameters for Dynamic AT
  use_fosc: False           # if True, use Dynamic AT
  fosc_max: 0.5             # maximum (initial) threshold for optimality gap
  dynamic_epoch: 30         # number of epochs that threshold linearly drops to zero

# ===================== parameters for random transform ===================== #
rand:
  rule: 'majority'
  temperature: 1

  seed: null
  clip: null
  # clip: [-1., 1.]
  # clip: [0., 1.]
  num_draws: 1
  # transforms: ['drop_pixel']
  # transforms: ['erase']
  # transforms: ['normal']
  transforms: ['uniform']
  # transforms: ['normal', 'shear', 'scale', 'rotate', 'translate']
  # transforms: ['normal', 'affine']
  # transforms: ['colorjitter']
  # transforms: ['colorjitter', 'motionblur', 'erase', 'shear', 'scale', 'rotate', 'translate']
  # transforms: ['motionblur']
  # transforms: ['rotate', 'motionblur', 'translate', 'colorjitter', 'shear', 'scale']
  # transforms: ['drop_pixel', 'rotate', 'translate', 'colorjitter', 'shear', 'scale']
  # transforms: ['hflip', 'drop_pixel', 'rotate', 'translate', 'colorjitter', 'shear', 'gamma', 'scale', 'grayscale']
  # transforms: ['hflip', 'drop_pixel', 'colorjitter', 'gamma', 'grayscale']
  # transforms: ['hflip', 'drop_pixel', 'colorjitter']
  # transforms: ['hflip', 'normal', 'colorjitter', 'gamma', 'grayscale', 'drop_pixel', 'affine']
  # transforms: ['medblur', 'hflip', 'normal', 'motionblur', 'gamma', 'laplacian', 'drop_pixel', 'gaussblur', 'affine', 'boxblur', 'sobel']
  affine:
    dist: 'uniform'
    alpha: 0.3
  boxblur:
    p: 0.2
    kernel_size: 5
  colorjitter:
    alpha: 0.5
  drop:
    p: 0.3
  drop_pixel:
    p: 0.5
  erase:
    # scale: [0.1, 0.2]    # scale of area
    scale: [0.0000001, 0.5]
    ratio: [0.5, 2.0]    # aspect ratio of the erasing box
  gamma:
    dist: 'uniform'
    alpha: 0.3
  gaussblur:
    p: 0.2
    kernel_size: 5
    sigma: 0.5
  # grayscale:
  #   p: 0.2
  hflip:
    p: 0.5
  laplacian:
    p: 0.2
    kernel_size: 5
  medblur:
    p: 0.2
    kernel_size: 5
  motionblur:
    p: 0.2
    kernel_size: 5
    angle: 90.0
    direction: 1.0
  normal:
    mean: 0.0
    std: 0.25
    # clip: [0., 1.]
    clip: null
  rotate:
    dist: 'uniform'
    alpha: 30
  scale:
    dist: 'uniform'
    alpha: 0.3
  shear:
    dist: 'uniform'
    alpha: 0.3
  sobel:
    p: 0.3
  translate:
    dist: 'uniform'
    alpha: 0.3
  uniform:
    range: [-0.3, 0.3]
