at:
  beta: 0
  clip: true
  dynamic_epoch: 30
  early_stop: false
  epsilon: 0.3
  final_gap: 1
  fosc_max: 0.5
  init_gap: 0
  linear_gap: null
  loss_func: ce
  method: pgd
  num_steps: 40
  p: inf
  rand_eps: 0
  random_start: true
  step_gap:
  - 30
  - 45
  - 60
  step_size: 0.02
  use_diff_rand_eps: false
  use_fosc: false
meta:
  data_path: ~/data/
  exp_id: 1
  gpu_id: '0'
  model_name: mnist_at_exp_seed_220_seed_220_seed_220
  save_path: ./
  seed: 220
train:
  batch_size: 128
  epochs: 5
  l2_reg: 0.0005
  learning_rate: 0.01
  lr_scheduler: step
  save_best_only: true
  save_epochs: 1
